[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "data-discovery"
description = "data-discovery Server - dbt CLI tools and discovery functionality"
readme = "README.md"
requires-python = ">=3.12"
version = "0.2.0"
authors = [
    { name = "forgxyz" },
]
dependencies = [
    "mcp==1.9.3",
    "aiohttp>=3.8.0",
]

[project.scripts]
fsc-dbt-mcp = "fsc_dbt_mcp.server:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0"
]
github = [
    "aiohttp>=3.8.0"
]

[tool.uv]
dev-dependencies = []